---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<!-- 
use this code for comments between chunks
-->


```{r, Installing Libraries}

library(tidyverse)
library(skimr)        ## install.packages("skimr")
#  dplyr is part of tidyverse -- library(dplyr)

#
#in console
#   str(df)
#   print(df, n=10)
#   
#   to make a df into tibble use x1 <- as_tibble(original_df)  
#   
#   dim(df) will show dimensions of the df
#   


```

###Read AVID slash wall data
```{r,read avid slash wall}

library(readxl)
raw_data_01 <- read_excel("avid_cleaned_gasline_sta_2018-2020.xlsx",
col_types = c("text", "text", "text",
"text", "numeric", "text", "text",
"numeric", "numeric", "numeric",
"numeric", "text", "text", "numeric",
"text", "numeric", "numeric"))

data02 <- raw_data_01 %>% 
  mutate_at(
    vars(harvest, inside_slash, inside_fence, plot, species, quad, tag),
    factor) %>% 
  select(!c(site_name, gps,quad,date2019))

#str(data02)
#need to change var=inside_fence for YES to yes

```

###Make the Data Tidy
```{r, make data tidy}

#create df with heights for only one year
#use bind_rows(df1, df2) to reaggregate

data2018 <- data02 %>% 
  select(!c(ht2019.july, ht2020.july)) %>% 
  rename(ht = ht2018.july) %>% 
  mutate(
    year = 2018
  ) %>% 
  drop_na(ht) %>% 
  mutate(ht2018.july = NULL) #this is not needed, the variable name was changed

data2019 <- data02 %>% 
  select(!c(ht2018.july, ht2020.july)) %>% 
  rename(ht = ht2019.july) %>% 
  mutate(
    year = 2019
  ) %>% 
  drop_na(ht) %>% 
  mutate(ht2019.july = NULL) #this is not needed, the variable name was changed

data2020 <- data02 %>% 
  select(!c(ht2018.july, ht2019.july)) %>% 
  rename(ht = ht2020.july) %>% 
  drop_na(ht) %>% 
  mutate(
    year = 2020
  )

avid_tidy <- 
  bind_rows(data2018, data2019, data2020)

write_csv(avid_tidy, "tidy_avid_2018-2020_gasline.csv")
 

```



