---
title: "AVID Boot Red Pine"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<!-- 
use this code for comments between chunks
-->


```{r, Installing Libraries}

library(tidyverse)
library(skimr)        ## install.packages("skimr")
library(readxl)

#  dplyr is part of tidyverse -- library(dplyr)

#
#in console
#   str(df)
#   print(df, n=10)
#   
#   to make a df into tibble use x1 <- as_tibble(original_df)  
#   
#   dim(df) will show dimensions of the df
#   


```

###Read AVID slash wall data Boot & Red Pine
```{r,read avid slash wall}

raw_data_01 <- read_excel("avid_boot_redpine_cleaned.2018-2021.xlsx", 
    sheet = "r_ready", col_types = c("text", 
        "text", "text", "text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric", "numeric"), skip = 3)

data02 <- raw_data_01 %>% 
  mutate_at(
    vars(harvest, inside_slash, inside_fence, plot, species, quad, tag),
    factor) %>% 
    rename(ht2020 = ht2020.April2021) %>% 
    mutate(inside_fence = recode(inside_fence, "YES" = "yes")) %>%  #old = new
    mutate(
      sub_cov_pct = sub_cov_pct * 100,
      canopy_cov_pct = canopy_cov_pct * 100
    ) %>% 
  select(!c(gps,quad)) %>% 
  filter(issue <1) %>% #removes tagged species with missing or dead data
  
  #filter(ht2018.july < 16.5) %>%  #removes potential stump sprouts
  #   used threshold 16.5" which was 75% percentile of Mike's gasline data
  #   creates file avid_tidy_short, "tidy_avid_short_2018-2020_boot_redpine.csv
  
  mutate(issue = NULL)

# 5/10/2021 decided to use all the data, not the "short" data.
# Pattern of hts similar to Mike's gas line data and the changes to statistical
# inference didn't warrant the confusion of explaining the logic and process.
# 
# In readme file, discussed the omission of red pine AVID data due to its
# instability for normal and heteroscadasticity.


summary(data02$ht2018.july)
hist(data02$ht2018.july)
```

###Make the Data Tidy
```{r, make data tidy}

#create df with heights for only one year
#use bind_rows(df1, df2) to reaggregate

data2018 <- data02 %>% 
  select(!c(ht2019.july, ht2020)) %>% 
  rename(ht = ht2018.july) %>% 
  mutate(
    year = 2018
  ) %>% 
  drop_na(ht) %>% 
  mutate(ht2018.july = NULL) #this removes variable, but is not needed, the variable name was changed

data2019 <- data02 %>% 
  select(!c(ht2018.july, ht2020)) %>% 
  rename(ht = ht2019.july) %>% 
  mutate(
    year = 2019
  ) %>% 
  drop_na(ht) 

data2020 <- data02 %>% 
  select(!c(ht2018.july, ht2019.july)) %>% 
  rename(ht = ht2020) %>% 
  drop_na(ht) %>% 
  mutate(
    year = 2020
  )


avid_tidy <- 
  bind_rows(data2018, data2019, data2020) %>% 
  mutate_at(
    vars(year), factor)

write_csv(avid_tidy, "tidy_avid_2018-2020_boot_redpine.csv")
  

```

```{r}
avid_tidy_plot_count <- avid_tidy %>% 
  filter(year == 2018) %>% 
  group_by(harvest, inside_slash, plot, species) %>% 
  summarize(
    n = n()
  ) %>% 
  arrange(harvest, inside_slash, species)

write_csv(avid_tidy_plot_count, "tidy_avid_2018_boot_pine_sample_sizes.csv")

x1 <- avid_tidy_plot_count %>% 
  group_by(harvest, inside_slash, species) %>% 
  summarize(
    sum = sum(n)
  )
```


