---
title: "AVID summary and graphs"
author: "Peter Smallidge"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- 
use this code for comments between chunks
-->


```{r, Installing Libraries}

library(tidyverse)
library(skimr)        ## install.packages("skimr")
library(readr)
#  dplyr is part of tidyverse -- library(dplyr)

#
#in console
#   str(df)
#   print(df, n=10)
#   
#   to make a df into tibble use x1 <- as_tibble(original_df)  
#   
#   dim(df) will show dimensions of the df
#   


```


###Read tidy CSV, merge Mike and Katie data
```{r, input Boot Red Pine tidy data}

library(readr)
data_boot_redpine <- read_csv("tidy_avid_short_2018-2020_boot_redpine.csv") #remove "_short"
data_boot_redpine <- read_csv("tidy_avid_2018-2020_boot_redpine.csv") #removed "_short"

boot_redpine <- data_boot_redpine %>% #Data Mike collected 2021 from Katie's 2018-2019 plots
    # the "_short" from the input/tidy r-code, retains <16.5 " to avoid stump sprouts
  mutate_at(
    vars(harvest, year, inside_slash, inside_fence, plot, species, tag, year),
    factor) %>% 
 #filter(issue != "1") %>%  variable "issue" was removed in the input/tidy file code
 mutate(inside_fence = recode(inside_fence, "YES" = "yes")) #old = new


data_sta_rd <- read_csv("tidy_avid_2018-2020_gasline.csv") %>% # From Mike's AVID data
  mutate_at(
    vars(harvest, year, inside_slash, inside_fence, plot, species, tag, year),
    factor) %>% 
  filter(!c(harvest == "gas_line")) %>% 
  filter(c(harvest == "sta_rd"))


data_station_pine <- bind_rows(data_sta_rd, boot_redpine) %>% 
  filter(harvest %in% c("sta_rd", "red_pine", "boot", "wedge")) %>% 
  filter(harvest != "sta_rd" & species != "sm") %>%  #no SM inside slash at sta_rd
  filter(harvest != "sta_rd" & species != "ro") %>%  #no RO inside slash at sta_rd
  mutate(
    harv_agg = harvest
  ) %>% 
   mutate(
    harv_agg = recode(harv_agg, "boot" = "sta_rd", "wedge" = "sta_rd")
  )

data_test <- data_station_pine %>% 
  filter(year == "2018")

hist(data_test$ht)

```

###Summary by Harvests: boot, wedge, sta_rd, red_pine
### remove _short, data from Mike's plots
```{r}

boot_redpine_summ <- boot_redpine %>% 
  mutate(
    ht_cm = ht * 2.54,
    basal_sqm = basal_area * 0.09290304
  ) %>% 
  filter(inside_fence == "no") %>% 
  mutate(inside_fence = NULL) %>% 
  group_by(harvest, species, inside_slash, year) %>% 
 summarize(
   n = n(),
   avg_ht = mean(ht),
   sd_ht = sd(ht),
   avg_basal = mean(basal_area),
   sd_basal = sd(basal_area),
   avg_ht_cm = mean(ht_cm),
   sd_ht_cm = sd(ht_cm),
   avg_basal_sqm = mean(basal_sqm),
   sd_basal_sqm = sd(basal_sqm),
   avg_grdCov = mean(ground_cov_pct),
   sd_grdCov = sd(ground_cov_pct),
   avg_subCov = mean(sub_cov_pct),
   sd_subCov = sd(sub_cov_pct),
   avg_canCov = mean(canopy_cov_pct),
   sd_canCov = sd(canopy_cov_pct)
  )

write_csv(boot_redpine_summ, "avid_boot_redpine_short_summary_data.csv")
 #
 #NOTE - boot_redpine does not have a fence treatment. That variable was removed
 #

#  summary(avid2020$ht)
  hist(boot_redpine$ht)
   

```



### Summary for Data Aggregated by Harvest (boot, wedge, = sta_rd |  red pine)
####  remove _short
```{r}

station_pine_summ <- data_station_pine %>% 
  mutate(
    ht_cm = ht * 2.54,
    basal_sqm = basal_area * 0.09290304
  ) %>% 
  filter(inside_fence == "no") %>% 
  mutate(inside_fence = NULL) %>% 
 group_by(harv_agg, species, inside_slash, year) %>% 
 summarize(
   n = n(),
   avg_ht = mean(ht),
   sd_ht = sd(ht),
   avg_basal = mean(basal_area),
   sd_basal = sd(basal_area),
   avg_ht_cm = mean(ht_cm),
   sd_ht_cm = sd(ht_cm),
   avg_basal_sqm = mean(basal_sqm),
   sd_basal_sqm = sd(basal_sqm),
   avg_grdCov = mean(ground_cov_pct),
   sd_grdCov = sd(ground_cov_pct),
   avg_subCov = mean(sub_cov_pct),
   sd_subCov = sd(sub_cov_pct),
   avg_canCov = mean(canopy_cov_pct),
   sd_canCov = sd(canopy_cov_pct)
  )

write_csv(station_pine_summ, "avid_station_pine_short_summary_data.csv")


#NOTE - boot_redpine does not have a fence treatment. That variable was removed


#  summary(avid2020$ht)
  hist(data_station_pine$ht)


```

<!-- 

There are two similiar data files
  - boot_redpine has harvest = boot, wedge and red pine
  - data_station_pine has harv_agg = sta_rd and red pine. boot and wedge aggregated.
  - for both df, the variable "inside_fence is removed
-->


###Visualizing the data
```{r}



boot_redpine_summ %>% 
  filter(species != "bc" & harvest != "sta_rd") %>% 
ggplot(aes(x=inside_slash, y = avg_ht, color=year)) +
  geom_point()+
  facet_grid(harvest ~ species)

station_pine_summ %>% 
  filter(species != "sm" ) %>% 
ggplot(aes(x=inside_slash, y = avg_ht, color=year)) +
  geom_point()+
  facet_grid(harv_agg ~ species)



```

<!-- 

#assessing if basal area associated with seedling ht unfenced
boot_redpine_summ %>% 
  filter(species != "bc" & harvest != "sta_rd" & inside_fence != "yes") %>% 
ggplot(aes(x=basal_area, y = ht, color=year)) +
  geom_point()+
  facet_grid(inside_slash ~ species)

#outside wall, assessing ground cover on seedling height
boot_redpine_summ %>% 
  filter(species != "bc" & harvest != "sta_rd" & inside_slash != "yes") %>% 
ggplot(aes(x=ground_cov_pct, y = ht, color=year)) +
  geom_point()+
  facet_grid(harvest ~ species)

#outside wall, assessing subcanopy cover on seedling height
boot_redpine_summ %>% 
  filter(species != "bc" & harvest != "sta_rd" & inside_slash != "yes") %>% 
ggplot(aes(x=sub_cov_pct, y = ht, color=year)) +
  geom_point()+
  facet_grid(harvest ~ species)

#outside wall, assessing canopy cover on seedling height
boot_redpine_summ %>% 
  filter(species != "bc" & harvest != "sta_rd" & inside_slash != "yes") %>% 
ggplot(aes(x=canopy_cov_pct, y = ht, color=year)) +
  geom_point()+
  facet_grid(harvest ~ species)
  
  -->




### coding factorials - df = boot_redpine
```{r, factorial boot_redpine}

#the "plot" below of predict(mymod) showed that the variability
#of height was low for small seedlings and increased with large seedlings.
#This is heteroscedasticity and common in ecological data. The typical fix is
#a log transformation 
#
#


mod_boot_pine <- lm(ht~inside_slash * harvest * species * year, 
            data=subset(boot_redpine))




#The original model was run without log transformation of "ht".   , species != "bc" & harvest != "sta_rd"
#The histogram of residuals was adequate, but the heteroscedasticity
#was prominently fanned. The model was thus rerun with log transformation

hist(residuals(mod_boot_pine))  #appears normally distributed

#a log transformation will the distribution of residuals more normal
#note the high and low x-axis values 


plot(predict(mod_boot_pine),residuals(mod_boot_pine)) #this tests heteroscedasticity
# there is a strong "fan" pattern. ht will be log transformed.
# log transformation wasn't effective at removing heteroscedasticity

summary(mod_boot_pine)
anova(mod_boot_pine)
library(emmeans)

#Estimated Marginal Means
emmeans(mod_boot_pine,~ inside_slash * harvest * species * year, type = "response")
#using type="response" reverse transforms log(ht)



#emmip = Estimate Marginal Means Interaction Plot
#No Fence vs. Yes Fence, and Without vs. With Slash Wall
emmip(mod_boot_pine, year ~ inside_slash | species + harvest, type = "response", CIs=TRUE)



#emmip = Estimate Marginal Means Interaction Plot
#No Fence vs. Yes Fence, and Without vs. With Slash Wall
emmip(mod_boot_pine, harvest ~ inside_slash | species + year, type = "response", CIs=TRUE)

#pairwise looks at responses of pairs of the variable after the ~
#pairwise "inside_fence" assesses if the fence matters by slash x species x year
emmeans(mod_boot_pine,pairwise ~ harvest | inside_slash * species * year, type = "response")


#pairwise "inside_slash" assesses if the slash matters by fence x species x year
emmeans(mod_boot_pine,pairwise ~ inside_slash | harvest * species * year, type = "response")

```



### coding factorials - df = data_station_pine (Mike + Katie Data)
```{r, factorial data_station_pine}

#the "plot" below of predict(mymod) showed that the variability
#of height was low for small seedlings and increased with large seedlings.
#This is heteroscedasticity and common in ecological data. The typical fix is
#a log transformation 
#
mod_station_pine <- lm(ht ~ inside_slash * harv_agg * species * year, 
            data=subset(data_station_pine))

hist(log(data_station_pine$ht))

#The original model was run without log transformation of "ht".
#The histogram of residuals was adequate, but the heteroscedasticity
#was prominently fanned. The model was thus rerun with log transformation

hist(residuals(mod_boot_pine))  #appears normally distributed

#a log transformation will the distribution of residuals more normal
#note the high and low x-axis values 


plot(predict(mod_boot_pine),residuals(mod_boot_pine)) #this tests heteroscedasticity
# there is a strong "fan" pattern. ht will be log transformed.
# log transformation created an error, perhaps too many NA

summary(mod_station_pine)
anova(mod_station_pine)
library(emmeans)

#Estimated Marginal Means
emmeans(mod_station_pine,~ inside_slash * harv_agg * species * year, type = "response")
#using type="response" reverse transforms log(ht)



#emmip = Estimate Marginal Means Interaction Plot
#No Fence vs. Yes Fence, and Without vs. With Slash Wall
emmip(mod_station_pine, year ~ inside_slash | species + harv_agg, type = "response", CIs=TRUE)



#emmip = Estimate Marginal Means Interaction Plot
#No Fence vs. Yes Fence, and Without vs. With Slash Wall
emmip(mod_station_pine, harv_agg ~ inside_slash | species + year, type = "response", CIs=TRUE)

#pairwise looks at responses of pairs of the variable after the ~
#pairwise "inside_fence" assesses if the fence matters by slash x species x year
emmeans(mod_station_pine,pairwise ~ harv_agg | inside_slash * species * year, type = "response")


#pairwise "inside_slash" assesses if the slash matters by fence x species x year
emmeans(mod_station_pine,pairwise ~ inside_slash | harv_agg * species * year, type = "response")

```




###Graphs of Seedling Response
```{r, graphs of seedling response}

p <- ggplot(filter(avid2020, year == 2020),
      aes(x = basal_area, y = ht))
p + geom_point(aes(color=species))+ facet_grid(~inside_slash)


  

```

